/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class frmLogin extends javax.swing.JFrame {
    public static final String URL = "jdbc:mysql://localhost:3306/fcristorey";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "";
    PreparedStatement ps;
    ResultSet rs;
    ImageIcon icono = new ImageIcon(getClass().getResource("/images/iconhead.png"));
    
    public static Connection getConnection(){
        Connection con = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
            if(con!=null){
                JOptionPane.showMessageDialog(null, "Solicitud enviada al sistema...");
            }
        }catch(Exception e){
            System.out.println(e);
        }
        return con;
    }
    
    int yMouse, xMouse;

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.setIconImage(icono.getImage());
        ImageIcon user = new ImageIcon(getClass().getResource("/images/account.png"));
        Icon adjuser = new ImageIcon(user.getImage().getScaledInstance(lblUser.getWidth(), 
                lblUser.getHeight(), Image.SCALE_SMOOTH));
        lblUser.setIcon(adjuser);
        
        ImageIcon pass = new ImageIcon(getClass().getResource("/images/key.png"));
        Icon adpass = new ImageIcon(pass.getImage().getScaledInstance(lblPsw.getWidth(), 
                lblPsw.getHeight(), Image.SCALE_SMOOTH));
        lblPsw.setIcon(adpass);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pswContra = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        lblPsw = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        lblDeco = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblUserDeco = new javax.swing.JLabel();
        lblContraDeco = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        pnlEcs = new javax.swing.JPanel();
        lblEcs = new javax.swing.JLabel();
        pnlMin = new javax.swing.JPanel();
        lblMin = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pswContra.setForeground(new java.awt.Color(204, 204, 204));
        pswContra.setText("************");
        pswContra.setToolTipText("");
        pswContra.setBorder(null);
        pswContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pswContraMousePressed(evt);
            }
        });
        pnlFondo.add(pswContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 300, 40));

        txtUser.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setText("Ingrese nombre de usuario");
        txtUser.setBorder(null);
        txtUser.setOpaque(false);
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserMousePressed(evt);
            }
        });
        pnlFondo.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 300, 40));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account.png"))); // NOI18N
        pnlFondo.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, 40));
        pnlFondo.add(lblPsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 40, 40));

        btnEntrar.setBackground(new java.awt.Color(83, 118, 165));
        btnEntrar.setForeground(new java.awt.Color(83, 118, 165));
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrarMouseExited(evt);
            }
        });
        btnEntrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTRAR");
        btnEntrar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        pnlFondo.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 100, 50));

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoxd.png"))); // NOI18N
        pnlFondo.add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 310, 90));

        lblDeco.setBackground(new java.awt.Color(51, 153, 255));
        lblDeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f8.jpg"))); // NOI18N
        pnlFondo.add(lblDeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 350, 500));
        pnlFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 300, 10));
        pnlFondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 300, 20));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setText("INICIAR SESIÓN");
        pnlFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, 40));

        lblUserDeco.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblUserDeco.setText("USUARIO");
        pnlFondo.add(lblUserDeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        lblContraDeco.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblContraDeco.setText("CONTRASEÑA");
        pnlFondo.add(lblContraDeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderMouseDragged(evt);
            }
        });
        pnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderMousePressed(evt);
            }
        });
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEcs.setBackground(new java.awt.Color(255, 255, 255));
        pnlEcs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEcs.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblEcs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcs.setText("X");
        lblEcs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEcs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEcsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEcsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEcsMouseExited(evt);
            }
        });
        pnlEcs.add(lblEcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        pnlHeader.add(pnlEcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        pnlMin.setBackground(new java.awt.Color(255, 255, 255));
        pnlMin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblMin.setForeground(new java.awt.Color(0, 0, 0));
        lblMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMin.setText("-");
        lblMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinMouseExited(evt);
            }
        });
        pnlMin.add(lblMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        pnlHeader.add(pnlMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        pnlFondo.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconito.png"))); // NOI18N
        pnlFondo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 50, 50));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblEcsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEcsMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblEcsMouseClicked

    private void pnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlHeaderMousePressed

    private void pnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pnlHeaderMouseDragged

    private void lblEcsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEcsMouseEntered
        pnlEcs.setBackground(Color.red);
        lblEcs.setForeground(Color.white);
    }//GEN-LAST:event_lblEcsMouseEntered

    private void lblEcsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEcsMouseExited
        pnlEcs.setBackground(Color.white);
        lblEcs.setForeground(Color.black);
    }//GEN-LAST:event_lblEcsMouseExited

    private void txtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMousePressed
        if(txtUser.getText().equals("Ingrese nombre de usuario")){
        txtUser.setText("");
        txtUser.setForeground(Color.black);
        }
        
        if(String.valueOf(pswContra.getPassword()).isEmpty()){
        pswContra.setText("************");
        pswContra.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtUserMousePressed

    private void pswContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswContraMousePressed
        if(txtUser.getText().isEmpty()){
        txtUser.setText("Ingrese nombre de usuario");
        txtUser.setForeground(Color.LIGHT_GRAY);
        }
        
        if(String.valueOf(pswContra.getPassword()).equals("************")){
        pswContra.setText("");
        pswContra.setForeground(Color.black);
        }
    }//GEN-LAST:event_pswContraMousePressed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        Connection con = null;
       try{
           con = getConnection();
           ps = con.prepareStatement("SELECT user, pass FROM Usuarios"
                   + " WHERE user = ?"
                   + " AND pass = ?");
          final String usuario = txtUser.getText().toString();
          final String pass = pswContra.getText().toString();
          ps.setString(1, usuario);
          ps.setString(2, pass);
          rs = ps.executeQuery();
          
          if(rs.next()){
              JOptionPane.showMessageDialog(null, "Acceso concedido");
              this.dispose();
              frmProductos a = new frmProductos();
              a.user = usuario;
              a.lblHoli.setText("Bienvenid@ "+ a.user);
              a.setVisible(true);
          }
          else{
              JOptionPane.showMessageDialog(null, "Acceso denegado o usuario inexistente.");
          }
          
       }catch(SQLException e){
           System.err.println(e.toString());
       }
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered
        btnEntrar.setBackground(new Color(59,72,78));
    }//GEN-LAST:event_btnEntrarMouseEntered

    private void btnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseExited
        btnEntrar.setBackground(new Color(83,118,165));
    }//GEN-LAST:event_btnEntrarMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jLabel1.setFocusable(true);
    }//GEN-LAST:event_formWindowActivated

    
    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseEntered
        pnlMin.setBackground(Color.BLUE);
        lblMin.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblMinMouseEntered

    private void lblMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseExited
        pnlMin.setBackground(new Color(255,255,255));
        lblMin.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblMinMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContraDeco;
    private javax.swing.JLabel lblDeco;
    private javax.swing.JLabel lblEcs;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblPsw;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserDeco;
    private javax.swing.JPanel pnlEcs;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMin;
    private javax.swing.JPasswordField pswContra;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
