/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import TablaRender.ColorCelda;
import javax.swing.ImageIcon;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static main.frmLogin.PASSWORD;
import static main.frmLogin.URL;
import static main.frmLogin.USERNAME;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author pc
 */


public class frmProductos extends javax.swing.JFrame {
    
    

    /**
     * Creates new form frmProductos
     */
    java.sql.Date lacadu;
    ArrayList<Integer> ids = new ArrayList();
    Date caducidad;
    int xMouse, yMouse, ans,e;
    PreparedStatement ps;
    ResultSet rs;
    ImageIcon icono = new ImageIcon(getClass().getResource("/images/iconhead.png"));
    
    public static Connection getConnection(){
        Connection con = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
            if(con!=null){
                System.out.println("Miau");
            }
        }catch(Exception e){
            System.out.println(e);
        }
        return con;
    }
    
    String user = "";
    public frmProductos() {
        initComponents();
        this.setIconImage(icono.getImage());
        btnConfirmar.setEnabled(false);
        btnConfirmar.setVisible(false);
        pnlAdmin.setVisible(false);    
        btnRefrescar.setVisible(false);
        Connection con = null;
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            tblProd.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs=null;
            con = getConnection();
            String sql = "SELECT prod_id, prod_nom, prod_uni, prod_cate, DATE_FORMAT(prod_cadu, '%d/%m/%Y') AS prod_cadu, prod_prov "
                    + "FROM productos";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData info = (ResultSetMetaData) rs.getMetaData();
            int cantcolum = info.getColumnCount();
            
            modelo.addColumn("ID_Producto");
            modelo.addColumn("Nombre");
            modelo.addColumn("Unidades");
            modelo.addColumn("Categoria");
            modelo.addColumn("Caducidad");
            modelo.addColumn("Proveedor");
            
            int[] anchos = {20,50,20,30,20,50};
            for(int i = 0; i<tblProd.getColumnCount(); i++ ){
                tblProd.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }
            
            while(rs.next()){
                Object[] filas = new Object[cantcolum];
                for(int i=0; i<cantcolum; i++){
                    filas[i] = rs.getObject(i+1);
                }
                modelo.addRow(filas);                
            }
            con.close();
        }catch(SQLException ex){
            System.err.println(ex.toString());
        }
        tblProd.setEnabled(false);
        
        //Lista por si se modificará la ID de algun producto.
        for(int n = 0; n < tblProd.getRowCount() ; n++){
            int f = 0;
            f = Integer.valueOf(tblProd.getValueAt(n, 0).toString());
            ids.add(f);
            }
            System.out.println(ids);    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        scpTabla = new javax.swing.JScrollPane();
        tblProd = new ColorCelda();
        lblHoli = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        btnRefrescar = new javax.swing.JPanel();
        lblRefrescar = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();
        cboCaducidad = new javax.swing.JComboBox<>();
        lblFiltDeco2 = new javax.swing.JLabel();
        lblFiltDeco = new javax.swing.JLabel();
        lblFiltDeco1 = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        btnBaja = new javax.swing.JPanel();
        lblBaja = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JPanel();
        lblAceptar = new javax.swing.JLabel();
        btnEdit = new javax.swing.JPanel();
        lblEdit = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JPanel();
        lblConfirmar = new javax.swing.JLabel();
        btnAlta = new javax.swing.JPanel();
        lblAlta = new javax.swing.JLabel();
        lblAdminMan = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        pnlEcs = new javax.swing.JPanel();
        lblEcs = new javax.swing.JLabel();
        pnlMin = new javax.swing.JPanel();
        lblMin = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlProveedor = new javax.swing.JPanel();
        lblProveedor = new javax.swing.JLabel();
        pnlCred = new javax.swing.JPanel();
        lblCred = new javax.swing.JLabel();
        pnlTicket = new javax.swing.JPanel();
        lblTicket = new javax.swing.JLabel();
        lblFondito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(747, 600));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProd.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProd.setOpaque(false);
        scpTabla.setViewportView(tblProd);

        pnlFondo.add(scpTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 750, 230));

        lblHoli.setFont(new java.awt.Font("Roboto Thin", 1, 14)); // NOI18N
        lblHoli.setForeground(new java.awt.Color(255, 255, 255));
        pnlFondo.add(lblHoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 30));

        btnBuscar.setBackground(new java.awt.Color(83, 118, 165));
        btnBuscar.setForeground(new java.awt.Color(83, 118, 165));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscar.setText("BUSCAR POR..");
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuscarMouseExited(evt);
            }
        });
        btnBuscar.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        pnlFondo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 120, 50));

        btnRefrescar.setBackground(new java.awt.Color(83, 118, 165));
        btnRefrescar.setForeground(new java.awt.Color(83, 118, 165));
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefrescar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRefrescar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        lblRefrescar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefrescar.setText("VER TODO");
        lblRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRefrescarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRefrescarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRefrescarMouseExited(evt);
            }
        });
        btnRefrescar.add(lblRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        pnlFondo.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 120, 50));

        cboCategoria.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antibioticos", "Libre de receta", "Venta libre", "Cuidado personal" }));
        cboCategoria.setBorder(null);
        cboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriaActionPerformed(evt);
            }
        });
        pnlFondo.add(cboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        cboCaducidad.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        cboCaducidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A punto", "Caducados" }));
        cboCaducidad.setBorder(null);
        cboCaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCaducidadActionPerformed(evt);
            }
        });
        pnlFondo.add(cboCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        lblFiltDeco2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblFiltDeco2.setForeground(new java.awt.Color(204, 204, 204));
        lblFiltDeco2.setText("CATEGORÍA");
        pnlFondo.add(lblFiltDeco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        lblFiltDeco.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblFiltDeco.setForeground(new java.awt.Color(204, 204, 204));
        lblFiltDeco.setText("CADUCIDAD");
        pnlFondo.add(lblFiltDeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        lblFiltDeco1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblFiltDeco1.setForeground(new java.awt.Color(204, 204, 204));
        lblFiltDeco1.setText("FILTROS DE BÚSQUEDA");
        pnlFondo.add(lblFiltDeco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        pnlAdmin.setOpaque(false);
        pnlAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBaja.setBackground(new java.awt.Color(59, 72, 78));
        btnBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBaja.setBackground(new java.awt.Color(59, 72, 78));
        lblBaja.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblBaja.setForeground(new java.awt.Color(255, 255, 255));
        lblBaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaja.setText("BAJA");
        lblBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBajaMouseExited(evt);
            }
        });
        btnBaja.add(lblBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        pnlAdmin.add(btnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, 50));

        btnAceptar.setBackground(new java.awt.Color(59, 72, 78));
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAceptar.setBackground(new java.awt.Color(59, 72, 78));
        lblAceptar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblAceptar.setForeground(new java.awt.Color(255, 255, 255));
        lblAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAceptar.setText("ACEPTAR");
        lblAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAceptarMouseExited(evt);
            }
        });
        btnAceptar.add(lblAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        pnlAdmin.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, 50));

        btnEdit.setBackground(new java.awt.Color(59, 72, 78));
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEdit.setBackground(new java.awt.Color(59, 72, 78));
        lblEdit.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEdit.setText("EDITAR");
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditMouseExited(evt);
            }
        });
        btnEdit.add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        pnlAdmin.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 50));

        btnSalir.setBackground(new java.awt.Color(59, 72, 78));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalir.setBackground(new java.awt.Color(59, 72, 78));
        lblSalir.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("SALIR");
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        btnSalir.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        pnlAdmin.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 50));

        btnConfirmar.setBackground(new java.awt.Color(59, 72, 78));
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConfirmar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmar.setText("CONFIRMAR");
        lblConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfirmarMouseExited(evt);
            }
        });
        btnConfirmar.add(lblConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        pnlAdmin.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, 50));

        btnAlta.setBackground(new java.awt.Color(59, 72, 78));
        btnAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlta.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlta.setText("ALTA");
        lblAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAltaMouseExited(evt);
            }
        });
        btnAlta.add(lblAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        pnlAdmin.add(btnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 50));

        lblAdminMan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblAdminMan.setForeground(new java.awt.Color(204, 204, 204));
        lblAdminMan.setText("ADMINIISTRACIÓN");
        pnlAdmin.add(lblAdminMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        pnlFondo.add(pnlAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 310, 240));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setOpaque(false);
        pnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderMouseDragged(evt);
            }
        });
        pnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderMousePressed(evt);
            }
        });
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEcs.setBackground(new java.awt.Color(18, 45, 90));
        pnlEcs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEcsMouseClicked(evt);
            }
        });
        pnlEcs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEcs.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblEcs.setForeground(new java.awt.Color(204, 204, 204));
        lblEcs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcs.setText("X");
        lblEcs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEcs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEcsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEcsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEcsMouseExited(evt);
            }
        });
        pnlEcs.add(lblEcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        pnlHeader.add(pnlEcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        pnlMin.setBackground(new java.awt.Color(18, 45, 90));
        pnlMin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblMin.setForeground(new java.awt.Color(204, 204, 204));
        lblMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMin.setText("-");
        lblMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinMouseExited(evt);
            }
        });
        pnlMin.add(lblMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        pnlHeader.add(pnlMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        pnlFondo.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 50));

        pnlMenu.setBackground(new java.awt.Color(19, 44, 89));
        pnlMenu.setForeground(new java.awt.Color(19, 44, 89));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENÚ");
        pnlMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        pnlProveedor.setBackground(new java.awt.Color(19, 44, 89));
        pnlProveedor.setMaximumSize(new java.awt.Dimension(106, 17));
        pnlProveedor.setMinimumSize(new java.awt.Dimension(106, 17));
        pnlProveedor.setPreferredSize(new java.awt.Dimension(106, 17));
        pnlProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProveedor.setFont(new java.awt.Font("Roboto Medium", 3, 14)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedor.setText("PROVEEDORES");
        lblProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProveedorMouseExited(evt);
            }
        });
        pnlProveedor.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        pnlMenu.add(pnlProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 40));

        pnlCred.setBackground(new java.awt.Color(19, 44, 89));
        pnlCred.setMaximumSize(new java.awt.Dimension(106, 17));
        pnlCred.setMinimumSize(new java.awt.Dimension(106, 17));
        pnlCred.setPreferredSize(new java.awt.Dimension(106, 17));
        pnlCred.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCred.setFont(new java.awt.Font("Roboto Medium", 3, 14)); // NOI18N
        lblCred.setForeground(new java.awt.Color(255, 255, 255));
        lblCred.setText("CRÉDITO");
        lblCred.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCredMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCredMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCredMouseExited(evt);
            }
        });
        pnlCred.add(lblCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        pnlMenu.add(pnlCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 40));

        pnlTicket.setBackground(new java.awt.Color(19, 44, 89));
        pnlTicket.setMaximumSize(new java.awt.Dimension(106, 17));
        pnlTicket.setMinimumSize(new java.awt.Dimension(106, 17));
        pnlTicket.setPreferredSize(new java.awt.Dimension(106, 17));
        pnlTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTicket.setFont(new java.awt.Font("Roboto Medium", 3, 14)); // NOI18N
        lblTicket.setForeground(new java.awt.Color(255, 255, 255));
        lblTicket.setText("TICKETS");
        lblTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTicketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTicketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTicketMouseExited(evt);
            }
        });
        pnlTicket.add(lblTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        pnlMenu.add(pnlTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 40));

        pnlFondo.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 230));

        lblFondito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f5.jpg"))); // NOI18N
        lblFondito.setMaximumSize(new java.awt.Dimension(950, 710));
        lblFondito.setMinimumSize(new java.awt.Dimension(950, 710));
        lblFondito.setPreferredSize(new java.awt.Dimension(950, 710));
        pnlFondo.add(lblFondito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 710));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(user.equals("Edgar") || user.equals("Max"))
            pnlAdmin.setVisible(true);
        else
            pnlAdmin.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void lblEcsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEcsMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblEcsMouseClicked

    private void lblEcsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEcsMouseEntered
        pnlEcs.setBackground(Color.red);
        lblEcs.setForeground(Color.white);
    }//GEN-LAST:event_lblEcsMouseEntered

    private void lblEcsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEcsMouseExited
        pnlEcs.setBackground(new Color(18,45,90));
        lblEcs.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_lblEcsMouseExited

    private void pnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pnlHeaderMouseDragged

    private void pnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlHeaderMousePressed

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        btnSalir.setVisible(true);
        btnSalir.setEnabled(true);
        btnEdit.setEnabled(false);
        btnEdit.setVisible(false);
        btnConfirmar.setEnabled(true);
        btnConfirmar.setVisible(true);
        tblProd.setEnabled(true);
    }//GEN-LAST:event_lblEditMouseClicked

    private void lblConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmarMouseClicked
        Connection con = null;
        ans = JOptionPane.showOptionDialog(this, "¿Los cambios son correctos?",
                "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                iconito("/images/signo-de-interrogacion.png", 40, 40), new Object[]{"No", "Correctos"}, "Correctos");
        if(ans==1){
            btnConfirmar.setVisible(false);
            btnConfirmar.setEnabled(false);
            btnEdit.setEnabled(true);
            btnEdit.setVisible(true);
            tblProd.setEnabled(false);
            lblFiltDeco.setFocusable(true);
            //UPDATE de la base de datos
            try{
                con = getConnection();
                for(int i = 0;i < tblProd.getRowCount(); i++){
                    ps = con.prepareStatement("UPDATE productos SET prod_id = ?, "
                            + "prod_nom = ?, prod_uni = ?, prod_cate = ?, prod_cadu = ?, prod_prov = ?"
                            + "WHERE prod_id = ?");
                    ps.setInt(1, Integer.valueOf(tblProd.getValueAt(i, 0).toString()));
                    
                    ps.setString(2, tblProd.getValueAt(i, 1).toString());
                    
                    ps.setInt(3, Integer.valueOf(tblProd.getValueAt(i, 2).toString()));
                    
                    ps.setString(4, tblProd.getValueAt(i, 3).toString());
                    
                    ps.setDate(5, Date.valueOf(tblProd.getValueAt(i, 4).toString()));
                    
                    ps.setString(6, tblProd.getValueAt(i, 5).toString());
                    
                    ps.setInt(7, ids.get(i));
                    ps.executeUpdate();
                }
                
                con.close();
            }catch(Exception ex){
                System.err.println(ex);
            }
            
        }
        else{
            btnConfirmar.setVisible(true);
            btnConfirmar.setEnabled(true);
            tblProd.setEnabled(true);
        }
    }//GEN-LAST:event_lblConfirmarMouseClicked

    private void lblEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseEntered
        btnEdit.setBackground(new Color(83,118,165));
    }//GEN-LAST:event_lblEditMouseEntered

    private void lblEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseExited
        btnEdit.setBackground(new Color(59,72,78));
    }//GEN-LAST:event_lblEditMouseExited

    private void lblConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmarMouseEntered
        btnConfirmar.setBackground(new Color(83,118,165));
    }//GEN-LAST:event_lblConfirmarMouseEntered

    private void lblConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmarMouseExited
        btnConfirmar.setBackground(new Color(59,72,78));
    }//GEN-LAST:event_lblConfirmarMouseExited

    public Icon iconito(String path, int width, int height){
    Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage()
    .getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH));
    return img;
    }
    
    private void lblAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaMouseClicked
        Connection con = null;
        do{
        JTextField nombreprod = new JTextField();
        JTextField unidadesprod = new JTextField();
        JComboBox cateprod = new JComboBox();
        JTextField caduciprod = new JTextField();
        JTextField proveeprod = new JTextField();
        cateprod.addItem("Antibioticos");
        cateprod.addItem("Libre de receta");
        cateprod.addItem("Venta libre");
        cateprod.addItem("Cuidado personal");
        Object[] campos = {
            "Nombre:", nombreprod,
            "Unidades:", unidadesprod,
            "Categoria:", cateprod,
            "Caducidad:", caduciprod,
            "Proveedor:", proveeprod
        };
        int res = JOptionPane.showConfirmDialog(null, campos, "Alta de Producto",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
                iconito("/images/medicamento.png", 40, 40));
        if(res==0){
            
            if(nombreprod.getText().equals("") || unidadesprod.getText().equals("") || caduciprod.getText().equals("")
                   || proveeprod.getText().equals("")){
                JOptionPane.showMessageDialog(null, "No deje ningun campo vacio", "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            else{
            String nombre = nombreprod.getText();
            int unidades = Integer.valueOf(unidadesprod.getText());
            String cate = cateprod.getSelectedItem().toString();
            String cadu = caduciprod.getText();
            String prove = proveeprod.getText();
                 
            try{
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date fecha = formato.parse(cadu);
                java.sql.Date fecha2 = new java.sql.Date(fecha.getTime());
                con = getConnection();
                    ps = con.prepareStatement("INSERT INTO productos ("
                            + "prod_nom, prod_uni, prod_cate, prod_cadu, prod_prov) "
                            + "VALUES (?,?,?,?,?)");
                    ps.setString(1, nombre);
                    ps.setInt(2, unidades);
                    ps.setString(3, cate);
                    ps.setDate(4, fecha2);
                    ps.setString(5, prove);
                    int au = ps.executeUpdate();
                    if(au > 0) System.out.println("Buena");
                    else System.out.println("xd");
                
                con.close();
            }catch(SQLException | ParseException ex){
                System.err.println(ex);
            }
            int ans = JOptionPane.showOptionDialog(null, "¿Desea agregar otro producto?", "Pregunta",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, 
                    new Object[]{"No","Si"}, "");
                if(ans==1) e = 0;
                else e = 1;
            }
            
            
            }
            else{
            e = 1;
            }
        }while(e!=1);
        frmProductos a = new frmProductos();
        a.user = user;
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_lblAltaMouseClicked

    private void lblAltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaMouseEntered
        btnAlta.setBackground(new Color(83,118,165));
    }//GEN-LAST:event_lblAltaMouseEntered

    private void lblAltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaMouseExited
        btnAlta.setBackground(new Color(59,72,78));
    }//GEN-LAST:event_lblAltaMouseExited

    private void lblBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBajaMouseClicked
        // Eliminar producto
        JOptionPane.showMessageDialog(null, "Seleccione el producto a dar de baja",
        "Aviso", JOptionPane.INFORMATION_MESSAGE);
        btnBaja.setVisible(false);
        btnBaja.setEnabled(false);
        btnAceptar.setVisible(true);
        btnAceptar.setEnabled(true);
        btnSalir.setVisible(true);
        btnSalir.setEnabled(true);
        btnEdit.setEnabled(false);
        btnEdit.setVisible(false);
        tblProd.setEnabled(true);
    }//GEN-LAST:event_lblBajaMouseClicked

    private void lblBajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBajaMouseEntered
        btnBaja.setBackground(new Color(83,118,165));
    }//GEN-LAST:event_lblBajaMouseEntered

    private void lblBajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBajaMouseExited
        btnBaja.setBackground(new Color(59,72,78));
    }//GEN-LAST:event_lblBajaMouseExited

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        //Buscar producto
        JTextField filter = new JTextField();
        JComboBox opc = new JComboBox();
        opc.addItem("Nombre");
        opc.addItem("Unidades");
        opc.addItem("Proveedor");
        Object[] buscador = {
            "Escoja el tipo de campo quiere buscar:", opc,
            "Escriba el dato del campo a buscar:", filter
        };
        int res = JOptionPane.showConfirmDialog(null, buscador, "Buscar por.."
                    ,JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,
                    iconito("/images/lupa.png", 40, 40));
        if(res==0){
            btnRefrescar.setVisible(true);
            String datos = filter.getText();
            String opcion = opc.getSelectedItem().toString();
            Connection con = null;
            String sql = "";
            switch (opcion) {
                case "Nombre":
                    opcion = "prod_nom";
                    sql = "SELECT prod_id, prod_nom, prod_uni, prod_cate, DATE_FORMAT(prod_cadu, '%d/%m/%Y') AS prod_cadu, prod_prov"
                            + " FROM productos WHERE "+opcion+" = '"+datos+"'";
                    break;
                case "Unidades":
                    opcion = "prod_uni";
                    sql = "SELECT prod_id, prod_nom, prod_uni, prod_cate, DATE_FORMAT(prod_cadu, '%d/%m/%Y') AS prod_cadu, prod_prov"
                            + " FROM productos WHERE "+opcion+" >= "+datos+"";
                    break;
                case "Proveedor":
                    opcion = "prod_prov";
                    sql = "SELECT prod_id, prod_nom, prod_uni, prod_cate, DATE_FORMAT(prod_cadu, '%d/%m/%Y') AS prod_cadu, prod_prov"
                            + " FROM productos WHERE "+opcion+" = '"+datos+"'";
                    break;
                default:
                    break;
            }
            try{
                DefaultTableModel modelo = new DefaultTableModel();
                tblProd.setModel(modelo);
                ResultSet rs = null;
                PreparedStatement buscar = null;
                con = getConnection();
                buscar = con.prepareStatement(sql);
                rs = buscar.executeQuery();
                ResultSetMetaData info = (ResultSetMetaData) rs.getMetaData();
                int cantcolum = info.getColumnCount();
            
                modelo.addColumn("ID_Producto");
                modelo.addColumn("Nombre");
                modelo.addColumn("Unidades");
                modelo.addColumn("Categoria");
                modelo.addColumn("Caducidad");
                modelo.addColumn("Proveedor");
            
                int[] anchos = {20,50,20,30,20,50};
                for(int i = 0; i<tblProd.getColumnCount(); i++ ){
                    tblProd.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }
            
                while(rs.next()){
                    Object[] filas = new Object[cantcolum];
                    for(int i=0; i<cantcolum; i++){
                        filas[i] = rs.getObject(i+1);
                    }
                    modelo.addRow(filas);                
                }
                con.close();    
                
            }catch(SQLException i){
                System.err.println(i);
            }
        }
        else btnRefrescar.setVisible(false);
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void lblBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseEntered
        btnBuscar.setBackground(new Color(59,72,78));
    }//GEN-LAST:event_lblBuscarMouseEntered

    private void lblBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseExited
        btnBuscar.setBackground(new Color(83,118,165));
    }//GEN-LAST:event_lblBuscarMouseExited

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        btnSalir.setVisible(false);
        btnSalir.setEnabled(false);
        btnEdit.setEnabled(true);
        btnEdit.setVisible(true);
        btnConfirmar.setEnabled(false);
        btnConfirmar.setVisible(false);
        tblProd.setEnabled(false);
        lblFiltDeco.setFocusable(true);
        btnBaja.setVisible(true);
        btnAceptar.setVisible(false);
        btnAceptar.setEnabled(false);
        btnBaja.setVisible(true);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        btnSalir.setBackground(new Color(83,118,165));
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        btnSalir.setBackground(new Color(59,72,78));
    }//GEN-LAST:event_lblSalirMouseExited

    private void cboCaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCaducidadActionPerformed
        btnRefrescar.setVisible(true);
        Connection con = null;
        String datos = cboCaducidad.getSelectedItem().toString();
        String sql = "";
        if(datos.equals("A punto")){
            sql = "SELECT prod_id, prod_nom, prod_uni, "
                + "prod_cate, DATE_FORMAT(prod_cadu, '%d/%m/%Y') AS prod_cadu, prod_prov"
                    + " FROM productos WHERE"
                    + " DATEDIFF(prod_cadu, NOW()) <= 92";
        }
        else if(datos.equals("Caducados")){
            sql = "SELECT prod_id, prod_nom, prod_uni, "
                + "prod_cate, DATE_FORMAT(prod_cadu, '%d/%m/%Y') AS prod_cadu, prod_prov"
                    + " FROM productos WHERE"
                    + " prod_cadu <= NOW()";
        }
        try{
                DefaultTableModel modelo = new DefaultTableModel();
                tblProd.setModel(modelo);
                ResultSet rs = null;
                PreparedStatement buscar = null;
                
                con = getConnection();
                buscar = con.prepareStatement(sql);
                rs = buscar.executeQuery();
                ResultSetMetaData info = (ResultSetMetaData) rs.getMetaData();
                int cantcolum = info.getColumnCount();
            
                modelo.addColumn("ID_Producto");
                modelo.addColumn("Nombre");
                modelo.addColumn("Unidades");
                modelo.addColumn("Categoria");
                modelo.addColumn("Caducidad");
                modelo.addColumn("Proveedor");
            
                int[] anchos = {20,50,20,30,20,50};
                for(int i = 0; i<tblProd.getColumnCount(); i++ ){
                    tblProd.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }
            
                while(rs.next()){
                    Object[] filas = new Object[cantcolum];
                    for(int i=0; i<cantcolum; i++){
                        filas[i] = rs.getObject(i+1);
                    }
                    modelo.addRow(filas);                
                }
                con.close();    
                
            }catch(SQLException i){
                System.err.println(i);
            }
    }//GEN-LAST:event_cboCaducidadActionPerformed

    private void lblAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAceptarMouseClicked
        int res = JOptionPane.showConfirmDialog(null, "¿Esta segur@ de eliminar el producto seleccionado?",
                "Pregunta", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
                iconito("/images/signo-de-interrogacion.png", 40, 40));
        if(res==0){
            Connection con = null;
            int fila = tblProd.getSelectedRow();
            String valor = tblProd.getValueAt(fila, 0).toString();
            try{
                con = getConnection();
                PreparedStatement borrar = con.prepareStatement("DELETE FROM productos "
                        + "WHERE prod_id = '"+valor+"'");
                borrar.executeUpdate();
                
            }catch(SQLException u){
                System.err.println(u);
            }
        frmProductos a = new frmProductos();
        this.dispose();
        a.setVisible(true);
        }
    }//GEN-LAST:event_lblAceptarMouseClicked

    private void lblAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAceptarMouseEntered
        btnAceptar.setBackground(new Color(83,118,165));
    }//GEN-LAST:event_lblAceptarMouseEntered

    private void lblAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAceptarMouseExited
        btnAceptar.setBackground(new Color(59,72,78));
    }//GEN-LAST:event_lblAceptarMouseExited

    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
        btnRefrescar.setVisible(true);
        Connection con = null;
        String datos = cboCategoria.getSelectedItem().toString();
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            tblProd.setModel(modelo);
            ResultSet rs = null;
            PreparedStatement buscar = null;
            String sql = "SELECT prod_id, prod_nom, prod_uni, prod_cate, DATE_FORMAT(prod_cadu, '%d/%m/%Y') AS prod_cadu, prod_prov"
                    + " FROM productos WHERE"
                    + " prod_cate = '"+datos+"'";
            con = getConnection();
            buscar = con.prepareStatement(sql);
            rs = buscar.executeQuery();
            ResultSetMetaData info = (ResultSetMetaData) rs.getMetaData();
            int cantcolum = info.getColumnCount();
            
            modelo.addColumn("ID_Producto");
            modelo.addColumn("Nombre");
            modelo.addColumn("Unidades");
            modelo.addColumn("Categoria");
            modelo.addColumn("Caducidad");
            modelo.addColumn("Proveedor");
            
            int[] anchos = {20,50,20,30,20,50};
            for(int i = 0; i<tblProd.getColumnCount(); i++ ){
                tblProd.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }
            
            while(rs.next()){
                Object[] filas = new Object[cantcolum];
                for(int i=0; i<cantcolum; i++){
                    filas[i] = rs.getObject(i+1);
                }
                modelo.addRow(filas);                
            }
            con.close();    
                
        }catch(SQLException i){
            System.err.println(i);
        }
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void lblRefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefrescarMouseClicked
        frmProductos a = new frmProductos();
        this.dispose();
        a.user = user;
        a.setVisible(true);
    }//GEN-LAST:event_lblRefrescarMouseClicked

    private void lblRefrescarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefrescarMouseEntered
        btnRefrescar.setBackground(new Color(59,72,78));
    }//GEN-LAST:event_lblRefrescarMouseEntered

    private void lblRefrescarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefrescarMouseExited
        btnRefrescar.setBackground(new Color(83,118,165));
    }//GEN-LAST:event_lblRefrescarMouseExited

    private void lblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProveedorMouseClicked
        frmProv a = new frmProv();
        this.dispose();
        a.user = user;
        a.setVisible(true);
    }//GEN-LAST:event_lblProveedorMouseClicked

    private void lblProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProveedorMouseEntered
        pnlProveedor.setBackground(new Color(8,17,34));
    }//GEN-LAST:event_lblProveedorMouseEntered

    private void lblProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProveedorMouseExited
        pnlProveedor.setBackground(new Color(19,44,89));
    }//GEN-LAST:event_lblProveedorMouseExited

    private void lblCredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCredMouseClicked
        // frmCredito
    }//GEN-LAST:event_lblCredMouseClicked

    private void lblCredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCredMouseEntered
        pnlCred.setBackground(new Color(8,17,34));
    }//GEN-LAST:event_lblCredMouseEntered

    private void lblCredMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCredMouseExited
        pnlCred.setBackground(new Color(19,44,89));
    }//GEN-LAST:event_lblCredMouseExited

    private void lblTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTicketMouseClicked
        // frmTickets
    }//GEN-LAST:event_lblTicketMouseClicked

    private void lblTicketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTicketMouseEntered
        pnlTicket.setBackground(new Color(8,17,34));
    }//GEN-LAST:event_lblTicketMouseEntered

    private void lblTicketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTicketMouseExited
        pnlTicket.setBackground(new Color(19,44,89));
    }//GEN-LAST:event_lblTicketMouseExited

    private void pnlEcsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEcsMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pnlEcsMouseClicked

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseEntered
        pnlMin.setBackground(Color.BLUE);
        lblMin.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblMinMouseEntered

    private void lblMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseExited
        pnlMin.setBackground(new Color(18,45,90));
        lblMin.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_lblMinMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAceptar;
    private javax.swing.JPanel btnAlta;
    private javax.swing.JPanel btnBaja;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnConfirmar;
    private javax.swing.JPanel btnEdit;
    private javax.swing.JPanel btnRefrescar;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JComboBox<String> cboCaducidad;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAceptar;
    private javax.swing.JLabel lblAdminMan;
    private javax.swing.JLabel lblAlta;
    private javax.swing.JLabel lblBaja;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JLabel lblCred;
    private javax.swing.JLabel lblEcs;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblFiltDeco;
    private javax.swing.JLabel lblFiltDeco1;
    private javax.swing.JLabel lblFiltDeco2;
    private javax.swing.JLabel lblFondito;
    public javax.swing.JLabel lblHoli;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblRefrescar;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTicket;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlCred;
    private javax.swing.JPanel pnlEcs;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMin;
    private javax.swing.JPanel pnlProveedor;
    private javax.swing.JPanel pnlTicket;
    private javax.swing.JScrollPane scpTabla;
    private javax.swing.JTable tblProd;
    // End of variables declaration//GEN-END:variables
}
